#######################################################################################
# Book settings
title: Calculo en varias variables
author: M. Benítez, L. Hervella, A. Prieto and J. Ráfales  
email: ''
logo                        : "udc_logo.png"  # A path to the book logo
exclude_patterns            : ["README.md"]  # Patterns to skip when building the book. Can be glob-style (e.g. "*skip.ipynb")

#######################################################################################
# Execution settings
execute:
  execute_notebooks         : 'off'  # Whether to execute notebooks at build time. Must be one of ("auto", "force", "cache", "off")
  timeout                   : 600    # The maximum time (in seconds) each notebook cell is allowed to run.

#######################################################################################
# Extensiones tomadas del JB "Computational Mechanics"
parse:
  myst_enable_extensions: #true
    - amsmath
    - colon_fence
    - dollarmath
    - html_admonition
    - html_image
    - linkify
    - replacements
    - smartquotes
    - substitution
    - tasklist
    # - fancy_lists
  myst_dmath_double_inline: true

######################################################################
# Incluyo lo siguiente para los entornos definición, teorema, etc.
################
sphinx:
  extra_extensions:
    - sphinx_proof

#######################################################################################
# HTML-specific settings
html:
  udc_logo                  : "udc_logo.png"  # A path to a favicon image
  navbar_number_sections    : True  # Add a number to each section in your left navbar
  google_analytics_id       : "UA-148221575-1"  # A GA id that can be used to track book views.
  home_page_in_navbar       : false  # Whether to include your home page in the left Navigation Bar
  extra_footer : |
      <div>
      Esta obra está bajo una <a href="https://creativecommons.org/licenses/by/4.0/deed.es"> Licencia Creative Commons Atribución 4.0 Internacional </a>
      <a href="https://creativecommons.org/publicdomain/zero/1.0/deed.es_ES"><img src="https://i.creativecommons.org/l/by/4.0/88x31.png"></a>
      </div>

#######################################################################################
# Launch button settings
launch_buttons:
  binderhub_url             : "https://mybinder.org"  # The URL of the BinderHub (e.g., https://mybinder.org)
  notebook_interface        : "jupyterlab"
  
repository:
   url                       : https://github.com/LuisHervella/JB_Calculo2_UDC  # The URL to your book's repository
   branch                    : main  # Which branch of the repository should be used when creating links

# sphinx:
#   config:
#     html_extra_path: ['assets']